# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date publiee')),
            ],
        ),
        migrations.AddField(
            model_name='choix',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Sondage'),
        ),
    ]
