# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choix',
            name='sondage',
        ),
        migrations.DeleteModel(
            name='Choix',
        ),
        migrations.DeleteModel(
            name='Sondage',
        ),
    ]
